# ================================================================
# ServerBench Agent
# ================================================================

serverbench.agent.controller-url=${SERVERBENCH_AGENT_CONTROLLER_URL:http://localhost:8080}
serverbench.agent.id=${SERVERBENCH_AGENT_ID:}
serverbench.agent.version=${SERVERBENCH_AGENT_VERSION:1.0.0}
serverbench.agent.max-concurrency=${SERVERBENCH_AGENT_MAX_CONCURRENCY:1000}
serverbench.agent.heartbeat-interval-ms=${SERVERBENCH_AGENT_HEARTBEAT_INTERVAL_MS:5000}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

spring.main.banner-mode=off