# ================================================================
# ServerBench Agent
# ================================================================

serverbench.agent.controller-url=http://localhost:8080

# Leave empty to generate a unique identity for the current process.
serverbench.agent.id=

serverbench.agent.version=1.0.0
serverbench.agent.max-concurrency=1000
serverbench.agent.heartbeat-interval-ms=5000

spring.main.banner-mode=off
