<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.serverbench</groupId>
        <artifactId>serverbench</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>server-agent</artifactId>

    <name>ServerBench Agent</name>
    <description>ServerBench distributed load generator agent</description>

    <dependencies>

        <!-- Spring Boot core -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>4.1.1</version>
        </dependency>

        <!-- Jackson / ObjectMapper -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-json</artifactId>
            <version>4.1.1</version>
        </dependency>

        <!-- Kafka -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-kafka</artifactId>
            <version>4.1.1</version>
        </dependency>

        <!-- ServerBench engine -->
        <dependency>
            <groupId>com.serverbench</groupId>
            <artifactId>server-engine</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- Shared distributed contracts -->
        <dependency>
            <groupId>com.serverbench</groupId>
            <artifactId>server-distributed-contracts</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Tests -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>4.1.1</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>4.1.1</version>
            </plugin>

        </plugins>
    </build>

</project>